from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from datetime import datetime
import json
import re


def calculate_grade(score):

    if score >= 90:
        return "A+"

    elif score >= 80:
        return "A"

    elif score >= 70:
        return "B"

    elif score >= 60:
        return "C"

    return "D"


def generate_pdf_report(
    data,
    filename="website_report.pdf"
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]

    normal_style = styles["BodyText"]

    story = []

    website = data.get("Website", "")

    health = int(data.get("Health Score", 0))

    grade = calculate_grade(health)

    story.append(
        Paragraph(
            "TestPilot",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Professional Website Audit Report",
            heading_style
        )
    )

    story.append(
        Spacer(
            1,
            0.25 * inch
        )
    )

    story.append(
        Paragraph(
            f"<b>Website :</b> {website}",
            normal_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Generated :</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            normal_style
        )
    )

    story.append(
        Spacer(
            1,
            0.25 * inch
        )
    )
    # =========================
    # SCORE SUMMARY
    # =========================

    summary_data = [
        ["Metric", "Score"],
        ["Overall Grade", grade],
        ["Health Score", str(data.get("Health Score", 0))],
        ["SEO Score", str(data.get("SEO Score", 0))],
        ["Accessibility Score", str(data.get("Accessibility Score", 0))],
        ["Performance Score", str(data.get("Performance Score", 0))],
        ["Broken Links", str(data.get("Broken Links", 0))]
    ]

    summary_table = Table(
        summary_data,
        colWidths=[230, 180]
    )

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ("TOPPADDING", (0, 1), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 8),

            ("ALIGN", (1, 1), (1, -1), "CENTER")
        ])
    )

    story.append(summary_table)

    story.append(
        Spacer(
            1,
            0.3 * inch
        )
    )

    story.append(
        Paragraph(
            "Executive Summary",
            heading_style
        )
    )

    if health >= 90:
        summary = (
            "The website is in excellent condition. "
            "Performance, accessibility and SEO are well optimized."
        )

    elif health >= 75:
        summary = (
            "The website is healthy but there are a few improvements "
            "recommended for SEO and performance."
        )

    else:
        summary = (
            "The website requires optimization to improve quality, "
            "SEO and overall performance."
        )

    story.append(
        Paragraph(
            summary,
            normal_style
        )
    )

    story.append(
        Spacer(
            1,
            0.25 * inch
        )
    )

    story.append(
        Paragraph(
            "Detailed Results",
            heading_style
        )
    )
    # =========================
    # AI RECOMMENDATIONS
    # =========================

    story.append(
        Paragraph(
            "AI Recommendations",
            heading_style
        )
    )

    ai_text = data.get(
        "AI Suggestions",
        "No AI Suggestions Available."
    )

    ai_text = (
        ai_text
        .replace("\r\n", "<br/>")
        .replace("\n", "<br/>")
    )

    story.append(
        Paragraph(
            ai_text,
            normal_style
        )
    )

    story.append(
        Spacer(
            1,
            0.35 * inch
        )
    )

    # =========================
    # FOOTER
    # =========================

    story.append(
        Table(
            [[
                "Generated by TestPilot\n"
                "Professional Website Testing Platform"
            ]],
            colWidths=[420]
        )
    )

    footer = story[-1]

    footer.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1F4E79")),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ])
    )

    # =========================
    # BUILD PDF
    # =========================

    doc.build(story)

    return filename



def generate_code_pdf(
    data,
    filename="code_analysis_report.pdf"
):
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle
    )
  

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]

    normal = styles["BodyText"]

    story = []
    analysis = data.get("analysis", {})
    security = data.get("security_analysis", {})


    if isinstance(analysis, str):
        analysis = json.loads(analysis)

    if isinstance(security, str):   
        security = json.loads(security)

    score = analysis.get("score", 0)
    security_score = security.get("score", 0)
    print(type(analysis))
    print(analysis)

    story.append(
        Paragraph(
            "TestPilot",
            title
        )
    )

    story.append(
        Paragraph(
            "Professional Code Analysis Report",
            heading
        )
    )

    story.append(
        Spacer(1, 0.25 * inch)
    )

    story.append(
        Paragraph(
            f"<b>File :</b> {data.get('filename','')}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Language :</b> {data.get('language','')}",
            normal
        )
    )

    story.append(
        Paragraph(
            f"<b>Generated :</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            normal
        )
    )

    story.append(
        Spacer(1, 0.25 * inch)
    )

    summary = [
        ["Metric", "Value"],
        ["Code Score", str(score)],
        ["Security Score", str(security_score)]
    ]

    table = Table(
        summary,
        colWidths=[220, 180]
    )

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1F4E79")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.grey),
            ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),
            ("ALIGN", (1,1), (-1,-1), "CENTER")
        ])
    )

    story.append(table)

    story.append(
        Spacer(1,0.30*inch)
    )

    story.append(
        Paragraph(
            "Detected Issues",
            heading
        )
    )

    issues = analysis.get("issues", [])

    if isinstance(issues, str):
        try:
            issues = json.loads(issues)
        except:
            issues = [issues]

    if not issues:
        story.append(
            Paragraph(
                "No issues detected.",
                normal
            )
        )
    else:

        issue_table = [["#", "Issue"]]

        for i, issue in enumerate(issues, start=1):

            # Remove temp file path
            if ":" in issue:
                parts = issue.split(":", 3)
                if len(parts) >= 4:
                    issue = parts[3].strip()

            issue_table.append(
                [
                    str(i),
                    issue
                ]
            )

        t = Table(
            issue_table,
            colWidths=[40,360]
        )

        t.setStyle(
            TableStyle([
                ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1F4E79")),
                ("TEXTCOLOR",(0,0),(-1,0),colors.white),
                ("GRID",(0,0),(-1,-1),1,colors.grey),
                ("BACKGROUND",(0,1),(-1,-1),colors.beige)
            ])
        )

        story.append(t)

    story.append(
        Spacer(1,0.30*inch)
    )

    story.append(
        Paragraph(
            "Security Issues",
            heading
        )
    )

    sec = security.get("issues", [])

    if not sec:
        story.append(
            Paragraph(
                "No security issues detected.",
                normal
            )
        )
    else:
        for item in sec:
            story.append(
                Paragraph(
                    f"• {item}",
                    normal
                )
            )

    story.append(
        Spacer(1,0.30*inch)
    )

    story.append(
        Paragraph(
            "Severity Summary",
            heading
        )
    )

    severity = data.get("severity", {})

    # If severity comes as JSON string from DB, convert it
    if isinstance(severity, str):
        try:
            severity = json.loads(severity)
        except Exception:
            severity = {}

    sev_table = [
        ["Critical", severity.get("critical", 0)],
        ["High", severity.get("high", 0)],
        ["Medium", severity.get("medium", 0)],
        ["Low", severity.get("low", 0)]
    ]

    t = Table(
        sev_table,
        colWidths=[180,100]
    )

    t.setStyle(
        TableStyle([
            ("GRID",(0,0),(-1,-1),1,colors.grey),
            ("BACKGROUND",(0,0),(-1,-1),colors.whitesmoke)
        ])
    )

    story.append(t)

    story.append(
        Spacer(1,0.30*inch)
    )

    story.append(
        Paragraph(
            "AI Suggestions",
            heading
        )
    )

    ai = str(data.get("ai_suggestions", ""))

    try:

        ai = re.sub(r"```json|```", "", ai).strip()

        ai_json = json.loads(ai)

        for key, value in ai_json.items():

            story.append(
                Paragraph(
                    f"<b>{key}</b>",
                    heading
                )
            )

            if isinstance(value, list):

                for item in value:

                    if isinstance(item, dict):

                        text = " | ".join(
                            f"{k}: {v}"
                            for k, v in item.items()
                        )

                        story.append(
                            Paragraph(
                                f"• {text}",
                                normal
                            )
                        )

                    else:

                        story.append(
                            Paragraph(
                                f"• {item}",
                                normal
                            )
                        )

            else:

                story.append(
                    Paragraph(
                        str(value),
                        normal
                    )
                )

            story.append(
                Spacer(
                    1,
                    0.08 * inch
                )
            )

    except Exception:

        story.append(
            Paragraph(
                ai.replace("\n", "<br/>"),
                normal
            )
        )

    story.append(
        Spacer(1, 0.40 * inch)
    )
    # common footer for the document
    story.append(
        Spacer(1, 0.40 * inch)
    )

    footer = Table(
        [[
            "Generated by TestPilot"
        ]],
        colWidths=[420]
    )

    footer.setStyle(
        TableStyle([
            ("BACKGROUND",(0,0),(-1,-1),colors.HexColor("#1F4E79")),
            ("TEXTCOLOR",(0,0),(-1,-1),colors.white),
            ("ALIGN",(0,0),(-1,-1),"CENTER"),
            ("TOPPADDING",(0,0),(-1,-1),10),
            ("BOTTOMPADDING",(0,0),(-1,-1),10)
        ])
    )

    story.append(footer)

    doc.build(story)

    return filename